package com.example.fileprocessor.constant;

public enum FileProcessStatus {
    FILE_ACCEPTED,
    FIRST_VALIDATION_COMPLETED,
    FIRST_VALIDATION_FAILED,
    SECOND_VALIDATION_COMPLETED,
    SECOND_VALIDATION_FAILED,
    FILE_HAS_BEEN_UPLOADED
}
